version: '3.8'

services:
    postgres:
        image: postgres
        restart: always
        env_file:
            - .env
        volumes:
            # - ./pgdata:/var/lib/postgresql/data
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - app-network
        ports:
            - "5432:5432"
    # client:
    #     depends_on:
    #         - server
    # server:
    #     depends_on:
    #         - postgres
    
networks:
    app-network:
        driver: bridge